title: "Randy's Portfolio"
description: "Showcasing my projects and blogs"
theme: minima


social_links:
  - name: GitHub
    url: https://github.com/rpham037
  - name: LinkedIn
    url: https://www.linkedin.com/in/randypham2/